### ISSUE TITLE
New issue upon updating

### ISSUE THREAD

**Issue by ghbug** [jaredkrinke/luasmith#63]
Hi there,

Really nice progress to be seen and thank for implementing some of the issues we had discussed earlier. Unfortunately, I have been having a bit of trouble with running `luasmith` now following updating. This may be due to the way I have run the ebuild but I wonder if it might also just be that my code is now deprecated since last we spoke. The error as follows goes;

```bash
*** ERROR ***
[string "main.lua"]:895: Error filling in template "^categories/.-%.html$" on item "categories/creature.html":

	[string "../themes/website/date.lua"]:2: attempt to index upvalue '_ENV' (a nil value)

stack traceback:
	[C]: in function 'error'
	[string "main.lua"]:895: in function 'transform'
	[string "main.lua"]:498: in function 'process'
	[string "main.lua"]:1021: in function 'build'
	[string "main.lua"]:1051: in main chunk
```

Running `luasmith ../../dir/dir/theme.lua` yields the above. Curiously, the template referenced is different each time. Any help regarding this would be much appreciated, thank you.

**Comment by jaredkrinke** [comment]
Can you share `../themes/website/date.lua` (edit: and maybe any parent templates and the item itself)? It's not clear to me where `_ENV` is coming from or what it's for (edit: probably means that nil was passed to a template instead of a table--but why? Edit: no, that doesn't produce that error either).

Edit: not related:

~~I hit a similar-sounding issue. In my case, I had to split my `applyTemplates` step into two because I (unknowingly) needed to have one particular template run *before* any others. Specifically, the Atom feed template needed to run *before* the other templates, otherwise my header/footer would get inserted into some items of the Atom feed.~~

~~This is an unfortunate side-effect of changing the underlying architecture. Before, items would get processed in the same order, but now the order is unspecified/random. My pipeline issue was technically a bug, it just didn't matter before because I "got lucky" with the (previously consistent) item ordering.~~

**Comment by ghbug** [comment]
Hi Jared, thanks for your reply. Below is both the `theme.lua` file and the `date.lua` file.

Firstly, `theme.lua`. Would I be correct in thinking your suggestion would be to move the placement of `{ "^feed.xml$", fs.readThemeFile("feed.etlua") }` to the top of `applyTemplates` (or rather call it separately and first for this `.etlua` file)? I did try commenting this line out but unfortunately the error persists.

```lua
dates = fs.loadThemeFile("date.lua")()

-------------------------------------------------------------------------------
---------------------------- templates and helpers ----------------------------
-------------------------------------------------------------------------------

local htmlDateTemplate = etlua.compile([[<time datetime="<%= short %>"><%= long %></time>]])
local months = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }

function htmlDate(date)
	return htmlDateTemplate({ short = date, long = dates.formatDate(date) })
end

local keywordListTemplate = etlua.compile([[<%
for i, k in ipairs(keywords) do -%><% if i > 1 then %> | <% end %><a href="<%= pathToRoot %>categories/<%= k %>.html">#<%= k %></a>
<% end -%>]])
function keywordList(pathToRoot, keywords)
	return keywordListTemplate({ pathToRoot = pathToRoot, keywords = keywords })
end

local postListTemplate = etlua.compile([[<% local lastYear = nil -%>
<% for i, item in ipairs(table.sortBy(items, "date", true)) do 
	local year = string.match(item.date, "^(%d%d%d%d)")
	if lastYear ~= year then
		if lastYear ~= nil then -%>
</ul>
<% end -%>
<h1><%= year %></h1>
<ul>
<%
	lastYear = year
end
-%>
<li><%- htmlDate(item.date) .. " " %><a href="<%= pathToRoot %><%= item.path %>"><%= item.title %></a></li>
<% end -%>
<% if #items > 0 then -%>
</ul>
<% end -%>
]])
function postList(self)
	return postListTemplate({ pathToRoot = self.pathToRoot, items = self.items })
end

-------------------------------------------------------------------------------
----------------------------------- metadata ----------------------------------
-------------------------------------------------------------------------------

local site = {
	title = "untitled",
	url = "https://example.com/",
}

local siteOverrides = fs.loadThemeFile("site.lua")
if siteOverrides then
	table.merge(siteOverrides(), site)
end

local source = args[3] or "content"
local destination = args[4] or "out"


return {
	readFromSource(source),

	-- key is path, value content
	injectFiles({["style.css"] = css }),

	-- md to html
	processMarkdown(),
	omitWhen(function (item) return item.draft or item.path == "site.lua" end),

	-- aggregate all .html to items in for loop
	aggregate("feed.xml", "%.html$"),
	aggregate("index.html", "%.html$"),
	aggregate("about.html", "%.html$"),

	-- custom title
	createIndexes(function (keyword) return "categories/" .. keyword .. ".html" end, "keywords", "%.html$"),
	deriveMetadata({ title = function (item) return item.key end}, "^categories/.-%.html$"),
	deriveMetadata({post = function (item) return item.key end}, "^%d.*%d"), 

	-- apply index to list
	-- add metadata
	injectMetadata({ site = site }),
	applyTemplates({
		{ "%.html$", fs.readThemeFile("post.etlua") },
		{ "^categories/.-%.html$", fs.readThemeFile("categories.etlua") },
		{ "^feed.xml$", fs.readThemeFile("feed.etlua") },
		{ "^index%.html$", fs.readThemeFile("blog.etlua") },
		{ "^about%.html$", fs.readThemeFile("about.etlua") },
	}),

	-- apply to .html
	applyTemplates({
		{"%.html$", fs.readThemeFile("outer.etlua")},
	}),

	checkLinks(),
	writeToDestination(destination),
}
```

And `date.lua` below. Please note that I have currently commented out the lines referring to `atomifyItemContent`; when I don't, I get a similar error (`attempt to index upvalue '_ENV' (a nil value)`) but the traceback in C refers to the function `dofile` instead of the function `error` as per this issue.

```lua
local function parseYamlDate(str)
	local year, month, day = string.match(str, "^(%d%d%d%d)-(%d%d)-(%d%d)")
	if year and month and day then
		return year, month, day
	else
		error("failed to parse date: " .. str)
	end
end

local function formatDate(str)
	local year, month, day = parseYamlDate(str)
	return day .. " " .. month .. " "
end

local function yamlDateToIso(str)
	local year, month, day = parseYamlDate(str)
	return year .. "-" .. month .. "-" .. day .. "T" .. "00" .. ":" .. "00" .. ":00.000Z"
end

local function atomRepathItemContent(item, prefix)
	local parts = {}
	local pathFromRoot = fs.directory(item.path)
	_parseHtml(item.content, function (event)
		local part = event.html

		-- Repath relative links, if needed
		if pathFromRoot ~= "" and event.attribute and event.value
			and((event.tag == "a" and event.attribute == "href") -- Check for links
			or (event.tag == "link" and event.attribute == "href")
			or (event.tag == "script" and event.attribute == "src")
			or (event.tag == "img" and event.attribute == "src"))
			and not string.find(event.value, ":") -- Local/relative links only
		then
			part = event.attribute .. "=\"" .. (prefix or "") .. fs.join(pathFromRoot, event.value) .. "\""
		end

		table.insert(parts, part)
	end)
	return table.concat(parts)
end

-- function atomifyItemContent(item, siteUrl)
--	return atomRepathItemContent(item, siteUrl)
-- end

return {
--	atomifyItemContent = atomifyItemContent,
	formatDate = formatDate,
	yamlDateToIso = yamlDateToIso,
}
```

Any help in this would be much appreciated, thank you.

**Comment by jaredkrinke** [comment]
> Firstly, `theme.lua`. Would I be correct in thinking your suggestion would be to move the placement of `{ "^feed.xml$", fs.readThemeFile("feed.etlua") }` to the top of `applyTemplates` (or rather call it separately and first for this `.etlua` file)?

Yes, this will fix a bug when generating the Atom feed. It shouldn't change your original issue, but it's a bug in my original sample code that breaks on the new version.

(Still thinking about your other issue...)

**Comment by ghbug** [comment]
Hi Jared, thank you for that. I have separated the feed line into its own `applyTemplates` call.

~~On that note, I realised there were a few inconsistencies in my code (though strangely it did run before all the same). Notably, as demonstrated above, there is no camelCase on one instance of `applyTemplates`, and similarly so for an instance of of `readThemeFile`, both near the end of `theme.lua`.~~

Please ignore the above, it appears I somehow only had this locally.

Thank you for your continued look into this, I really appreciate it.

**Comment by jaredkrinke** [comment]
Just to double-check: this exact site builds successfully on luasmith 0.6, but fails on 0.8, right? And Windows native build, right?

If so, **could you also share `categories.etlua` and maybe `creatures.md`?**

Those are the template and item in which the error is allegedly occurring.

The error claims that `date.lua` (specifically line 2, in the YAML date parser) is getting a nil environment, but I can't reproduce such an error, despite numerous attempts. It sounds like none of your templates are running successfully, but I don't see an obvious reason why (especially one related to the changes I've made recently).

## Note to self
> Running `luasmith ../../dir/dir/theme.lua` yields the above. Curiously, the template referenced is different each time. Any help regarding this would be much appreciated, thank you.

This is almost certainly different from the ordering issue I mentioned earlier. I suspect that you will consistently see an error, and the only reason the template is different is that *all* the templates are breaking, and you're just seeing the first error (which is random since order is unspecified now).

**Comment by ghbug** [comment]
Hi Jared, thank you for your comment. This site builds on `luasmith` 0.6 on Debian 12. The current target is `luasmith` 0.8 but I am using Gentoo and the command is invoked after installing `luasmith` as a package via a custom ebuild (which I would be happy to share if you would like).

As to the two files, I should mention that the error will mention a different file each time (sometimes `index.html`, for instance) but happy to include `categories.etlua`. I cannot find `creatures.md` and I suspect this is being made via `postList` in the `.etlua` file. Apologies for not being clearer on that. Please find the `categories.etlua` file below.

```lua
<header>
<h1><%= key %></h1>
</header>
<%- postList(self) %>
<footer>
<p>&crarr; <a href="<%= pathToRoot %>index.html">root</a>
</footer>
```

Now that I have isolated the feed line first, it consistently provides the error relating to this file so certainly in agreement with the note at the bottom of your comment, yes.

**Comment by jaredkrinke** [comment]
Still looking at this, but I can reproduce the error locally, with your files. I should figure out if I can get it to print out the full stack on these kinds of errors. By modifying the code, I'm inferring the stack as:

*  `categories.etlua`
* `postList()`
* `postListTemplate()`
* `htmlDate()`
* `dates.formatDate()`
* `parseYamlDate()`

**Comment by ghbug** [comment]
Hi Jared, thank you for that. If it would be possible to print out the full stack, that would be great. Just as an addendum to my previous comment, I downloaded the tarball release and tried running it directly to see if maybe it was an issue with my ebuild but unfortunately it yields the same error.

**Comment by jaredkrinke** [comment]
Yeah, I think it's a real issue. My current theory is that I managed to step on a Lua footgun where some of Lua's built-in functions distinguish between `nil` and "no argument". I didn't realize that mattered when fixing an unrelated bug. If I'm correct, then I'm surprised I managed to *not* hit this same issue with my built-in themes.

I'll look more later or tomorrow. Thanks!

**Comment by ghbug** [comment]
Hi Jared, thanks for looking into this and interesting to have come across something like that too! Hopefully not too unwieldy to manage or identify but thank you all the same and looking forward to seeing what the issue might be.

Thanks again!

**Comment by jaredkrinke** [comment]
Give this updated build a shot: [luasmith-env-err-linux-x86_64.tar.gz](https://github.com/user-attachments/files/29653483/luasmith-env-err-linux-x86_64.tar.gz)

If this fixes it, yeah, it was a real regression that was triggered by a subtle misunderstanding of how Lua's C API handles missing function arguments. It turns out that C code (and only C code, I think) can distinguish "no argument" from `nil`. It feels a lot like JavaScript's `undefined` vs `null` situation.

In a helper that I added, I treating those two cases the same, so `dates.lua` was receiving a `nil` environment instead of defaulting to the global environment. This made the `string.match()` call fail to find the `string` table, and that's what the error was trying to convey.

**Comment by ghbug** [comment]
Hi Jared, thank you for this new build.

I think it might be close to this perhaps, yes. Now running, I do get a few warnings about broken links (these persisted when I successfully built in 0.6 too) but then a `string` error, perhaps also related to the C API. The error I get is as follows.

```bash
WARN:	Broken link from "about.html" to "/wiki"
WARN:	Broken link from "about.html" to "/wiki"
WARN:	Broken link from "index.html" to "/about"
WARN:	Broken link from "index.html" to "/wiki"
*** ERROR ***
[string "main.lua"]:379: bad argument #1 to 'write' (string expected, got nil)
stack traceback:
	[C]: in function 'write'
	[string "main.lua"]:379: in function 'writeFile'
	[string "main.lua"]:567: in function 'process'
	[string "main.lua"]:1024: in function 'build'
	[string "main.lua"]:1054: in main chunk
```

Looking at the [line](https://github.com/jaredkrinke/luasmith/blob/main/main.lua#L379) in code, I suppose `content` is failing or `nil` here but I am not quite sure why. Hope that helps deduce this further!

**Comment by jaredkrinke** [comment]
That sounds like you've got an item that has no/nil `content` property. I should probably make the build fail in that case, with an error indicating the empty item's path.

**Comment by ghbug** [comment]
Hi Jared. That is curious. I have checked my `content` folder with `ls -R content/` but it only shows two files. Using `cat` on both of them yields a full file. Would something like the following be a minimal viable file?

```md
---
title: test
date: 2026-07-05
---

test
```

If so, I will delete the `content` folder contents temporarily and try with just that.

Edit: Testing the above unfortunately still yields an error.

**Comment by jaredkrinke** [comment]
In the past I had items without templates or items where the templates
didn’t compile result in content-less items and this error. I have a plan
to improve the error message in both cases so it’s more obvious which items
are breaking.

In case that helps in the mean time 🙂

**Comment by ghbug** [comment]
Hi Jared, thank you that is useful to know. For now, I am not quite sure what the issue is as despite having `content/test.md` with the contents being the same as above, I still get the error as before, so it would definitely be helpful to have the path of the offending item.

I wonder if that means, in my case, there might still be something incorrect with the theme files?

**Comment by jaredkrinke** [comment]
I've revamped the error logging, so it now should log the offending item (and also error out on template compilation errors).

Give this a try and see if it helps narrow down the error:

[luasmith-error-logging-linux-x86_64.tar.gz](https://github.com/user-attachments/files/29668325/luasmith-error-logging-linux-x86_64.tar.gz)

Also, if you can't find the error and think it's a regression, let me know if the exact same site builds on v0.6 (I don't recall if you had done that after the most recent update).

**Comment by ghbug** [comment]
Hi Jared, thank you for this updated build. I had a look at the site again and actually, I am not sure I did build successfully with `0.6`, I think it was definitely `0.5` though. Unfortunately, Gentoo does not seem to package Lua 5.2 which is what seems to be required for this to run. At present, I have Lua `5.4.8` installed.

To be clear, my bash is a bit messy given the file locations of everything. The luasmith file sits in a directory in `/home/username/luasmith` whilst the `content` folder for the site sits in a subdirectory; `/home/username/site/html/content`. Finally, the `theme.lua` file and its counterparts sits in a folder above the `content` folder; `/home/username/site/themes/theme.lua`.

Consequently, the command I am using is;

```bash
../../luasmith/luasmith ../themes/theme.lua
```

Hopefully this is fine syntax?

~~The error with the new error logging build is as follows;~~

<details>
<summary><del>Old error, please ignore</del></summary>

```bash
WARN:	Broken link from "about.html" to "/wiki"
WARN:	Broken link from "about.html" to "/wiki"
WARN:	Broken link from "index.html" to "/about"
WARN:	Broken link from "index.html" to "/wiki"
*** ERROR ***
While processing "feed.xml":

[string "main.lua"]:415: bad argument #1 to 'write' (string expected, got nil)
stack traceback:
	[string "main.lua"]:415: in function 'writeFile'
	[string "main.lua"]:609: in function 'process'
	[string "main.lua"]:1079: in function 'build'
	[string "main.lua"]:1120: in function <[string "main.lua"]:1112>
	[C]: in function 'xpcall'
	[string "main.lua"]:17: in function 'withErrorLogging'
	[string "main.lua"]:1112: in main chunk
```
</details>

~~In version `0.6`, I get an error too;~~

<details>
<summary><del>Old error, please ignore</del></summary>

```bash
WARN:	Broken link from "about.html" to "/wiki"
WARN:	Broken link from "about.html" to "/wiki"
WARN:	Broken link from "index.html" to "/about"
WARN:	Broken link from "index.html" to "/wiki"
*** ERROR ***
[string "main.lua"]:382: bad argument #1 to 'write' (string expected, got nil)
stack traceback:
	[C]: in function 'write'
	[string "main.lua"]:382: in function 'writeFile'
	[string "main.lua"]:507: in function 'process'
	[string "main.lua"]:918: in function 'build'
	[string "main.lua"]:948: in main chunk
```
</details>

~~Unfortunately, I am not sure what to do in this instance and apologies for not being of more help at the moment but happy to test anything else to validate the build!~~

Please ignore all of the above; I had forgotten to uncomment the parts referring to the feed generation. Now the site generates successfully and I managed to track down the parts that were uncommented (partially) through the new error logging so thank you for that. The only part it did not pick up on was the commented section in `theme.lua`, namely;

```lua
--	applyTemplates({
--		{ "^feed.xml$", fs.readThemeFile("feed.etlua") }
--	}),
```

**Comment by jaredkrinke** [comment]
Ah, yes, I was going to say that the (newly helpful) error is indicating that `feed.xml` doesn't have any content. Not applying a template would do that.

I've lost track. Does that resolve all of the issues you're seeing?

**Comment by ghbug** [comment]
I think that would resolve everything now, yes. Just curious, would it be possible to have error logging indicate a template may not have been applied in that edge case? No problem if it's out of scope and happy for this to be closed either way!

**Comment by jaredkrinke** [comment]
Well, I can't know if a template was *intended* to be applied but wasn't, but I had been thinking I should update the "can't write a nil file" code path to log an error saying something like that (and maybe mentioning templates) to make it more obvious what the problem is (instead of `bad argument #1 to 'write' (string expected, got nil)`).

**Comment by ghbug** [comment]
Hi Jared, apologies; yes that does make sense regarding existence versus (intended) application of templates. If the error log did mention something like that, I think that could be quite good, though I do not know if there might be other cases wherein the current wording is preferable or more appropriate.

**Comment by jaredkrinke** [comment]
I think everything in here has been resolved now. Feel free to open a new issue or discussion if not!
